apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: deepproblog
  name: deepproblog
  namespace: bedu01
spec:
  replicas: 1
  selector:
    matchLabels:
      run: deepproblog
  template:
    metadata:
      labels:
        run: deepproblog
    spec:

      containers:
      - name: ilasp
        image: ghcr.io/dfkibedu/deepproblog:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        - containerPort: 22
          name: ssh-port
          protocol: TCP
        volumeMounts:
        - mountPath: /tf
          name: volume-1-bedu01
      volumes:
        - name: volume-1-bedu01
          persistentVolumeClaim:
            claimName: bedu01-workspace
